version: '3'
services:
  database:
    container_name: hedgedoc
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.9
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@database:5432/hedgedoc
      - CMD_DOMAIN=192.168.1.146
      - CMD_URL_ADDPORT=true
      - CMD_PORT=3031
      - CMD_HOST=0.0.0.0
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      - "3031:3031"
    restart: always
    depends_on:
      - database
volumes:
  database:
  uploads:
